Algorithm updates to better match GSSS
spacetelescope/jwst-fgs-countrate pull request #19
Opened 2021-12-02 21:37 UTC by shanosborne

Changes:
* Only include SDSS or GSC data in 
    * Base it first on what was used to calculated JHK
    * Then base it on what data is present in the code
* J and K cannot be missing, but H can - raise an error in that case
    * If J,H, and K cannot be calculated, return -999 rather than raise an error
    * Add an error elsewhere only for J and K missing, not H
* Remove error that J, H, and K alone can’t be used to calculate cr/mag (they can)
* Remove setting edge bands to 0 if missing - GSSS didn’t do that
* Move all constants to their own file
* Add color check for g-z only (From Ed: do not use the (g,z) transforms when g-z > 5 and g-z < 0.)
* Add r-z conversion option after g-z to match Beverly’s code
* Update minimum version of code to python 3.6
* Remove dim stars from being used in any calculations (jhk and cr/mag)
* Add more tests

2021-12-07 18:13 UTC, kjbrooks requested changes
A few fairly minor comments. I think there is only one where a change is needed. So that it is written down, we discussed a few other changes/questions that needed to get clarified by others before this PR will be ready to merge.

2021-12-07 18:13 UTC, kjbrooks commented on fgscountrate/utils.py
> +    if g-z > 5 or g-z < -1:
In the notes that you have for this PR, you mentioned that g-z < 0 but this says < -1. Assuming this will always be integer, the only time this might be a problem is when g-z = -1, but it should still be consistent.

2021-12-07 20:50 UTC, shanosborne commented on fgscountrate/tests/test_calc_cr_mag.py
> +    """Test that when a band (SDSS_g) is missing, it's signal is set to 0"""
Ah right, so this test checked 2 bands at once (one from gsc2 and one from sdss) but now that the code only lets you use 1 of those surveys, you can't test removing both at the same time. So I just dropped one of them and made the name more vague.

2021-12-07 20:56 UTC, shanosborne commented on fgscountrate/utils.py
> +    if g-z > 5 or g-z < -1:
Quote 1:
>  I’ve found from my analysis of several pencil beams from GSC2.4.2, the transformation from SDSS to NIR J,H,K can be unreliable when:
> g – z > 5
> g – z < 0

Quote 2:
> Do not use the (g,z) transforms when g-z > 5 and g-z < 0.

Quote 3:
> its not the individual magnitudes than get us in trouble with the transformations, rather it’s the color differences, such as g-z > 5, or g-z < -1


Given the context of these emails (quote 1 came from an email sent to beverly asking for a change), I think it's safe to say that g-z < 0 and g-z > 5 is correct. I'll put in that change

2021-12-07 21:31 UTC, kjbrooks commented on fgscountrate/tests/test_calc_cr_mag.py
> +    """Test that when a band (SDSS_g) is missing, it's signal is set to 0"""
ah okay, sounds good

2021-12-15 18:02 UTC, kjbrooks approved these changes
looks good

2021-12-16 15:54 UTC, shanosborne commented
Last typo can be confirmed in the image of table 9 at the top of PR #18

2021-12-16 21:05 UTC, merged